### PR TITLE
HPCC-21564 Update Dockerfiles for HPCC-6.4.36-1 and HPCC-7.0.14-1

### PR DESCRIPTION
**Pull request by gfortil**
Signed-off-by: Godson Fortil <FortGo01@risk.regn.net>

### CODE REVIEW

**Comment by gfortil** [comment]
@xwang2713 please review.

**Review by xwang2713 — COMMENTED** [review]
@gfortil,  have we updated stack/README.md

**Comment by gfortil** [comment]
@xwang2713  yes

**Review by xwang2713 — APPROVED** [review]
Looks good

**Pull request merged**
