### PR TITLE
HPCC-21842 Update Dockerfiles for HPCC-7.0.24-1

### PR DESCRIPTION
**Pull request by gfortil**
@xwang2713 please review

### CODE REVIEW

**Comment by xwang2713** [comment]
@gfortil can this be updated to latest HPCC releases: 7.0.34-1 and 7.2.8-1

**Comment by gfortil** [comment]
@xwang2713 should I close PR and Jira to open a brand new ones for the latest version?

**Comment by richardkchapman** [comment]
Sounds sensible. We should automate this process so that the Docker files are updated as part of the tagging. In the longer term I think the docker support should be part of the core platform and standard builds.

**Comment by gfortil** [comment]
Issuing new PR

**Pull request closed without merging**
